export default function CycloidDetails({ drawingType }) {
  return (
    <div className="flex flex-col w-full text-gray-700">
      <b>➽ Cycloidal Curve: </b>
      A cycloidal curve is a mathematical curve generated by the motion of a point on the circumference of a rolling circle. It is widely used in engineering, mechanics, and kinematics for its smooth and unique properties. Below are the general details about cycloidal curves.<br /><br />
      <b>➽   Types of Cycloidal Curves:</b>
      &nbsp;&nbsp;  a. Cycloid: <br />
      &nbsp;&nbsp; b. Epicycloid: <br />
      &nbsp;&nbsp; c. Hypocycloid: <br />
      &nbsp;&nbsp; d. Trochoid: <br /><br />
      {drawingType === "cycloid" && (
        <div>
          <b>➽Cycloid :</b> <br />
          Cycloid is refers to a specific type of curve generated by a point on the circumference of a circle as the circle rolls along a straight line without slipping. It is often used in the study of kinematics, gear design, and motion paths.
          <br />
          <br />
          <b>➽Characteristics of a Cycloid:</b> <br />
          <b> Generation:</b><br />
          &nbsp;&nbsp;* A cycloid is traced by a fixed point on a circle as it rolls along a straight line.<br />
          <b> Shape:</b><br />
          &nbsp;&nbsp;* The curve is periodic, consisting of identical loops, each called a "wave" or "arch."<br />
          <b> Applications:</b><br />
          &nbsp;&nbsp;* Cycloidal curves are commonly used in the design of cam profiles, pendulum clocks, and cycloidal gears because of their smooth motion characteristics.<br /><br />
          <b>➽Variants of Cycloid:</b> <br />
          <b>Epicycloid:</b><br />
          &nbsp;&nbsp;* Generated when a circle rolls on the outside of another circle.<br />
          <b>Hypocycloid:</b><br />
          &nbsp;&nbsp;* Generated when a circle rolls on the inside of another circle.<br />
        </div>

      )}
 {drawingType === "epicycloid" && (
   <div>
<b>➽Epicycloid :</b><br />
An epicycloid is a type of cycloidal curve generated by a point on the circumference of a circle as it rolls along the outside of another fixed circle without slipping.<br /><br />
<b>➽Generating Circles:</b><br />
&nbsp;&nbsp;* Rolling Circle (Generator): The smaller circle that rolls.<br />
&nbsp;&nbsp;* Fixed Circle (Base): The stationary circle on which the smaller circle rolls.<br /><br />
<b>➽Equation (Parametric):</b><br />
&nbsp;If the radius of the fixed circle is R and the radius of the rolling circle is r, and the point on the rolling circle generates the curve:<br />
&nbsp;&nbsp;x=(R+r)cos.t-r.cos( (R+r/r)t)<br />
&nbsp;&nbsp;y=(R+r)sin.t-r.sin( (R+r/r)t)<br /><br />

<b>➽Advantages in Applications:</b><br />
&nbsp;&nbsp;*Smooth and continuous curves reduce mechanical wear.<br />
&nbsp;&nbsp;*Provides efficient and precise motion in mechanical systems.<br />
&nbsp;&nbsp;*Enhances the aesthetic and functional design in artistic and practical uses.<br /><br />
   </div>

 )}
      {drawingType === "hypocycloid" && (
        <div>
 <b>➽Hypocycloid :</b><br />
 A hypocycloid is a type of cycloidal curve generated by a point on the circumference of a circle as it rolls along the inside of another fixed circle without slipping.<br /><br />
 <b>➽ Generating Components:</b><br />
 &nbsp;&nbsp;*Rolling Circle (Generator): The smaller circle that rolls inside.<br />
 &nbsp;&nbsp;*Fixed Circle (Base): The larger stationary circle.  <br /><br />
 <b>➽Equation (Parametric):</b><br />
 &nbsp;If the radius of the fixed circle is R and the radius of the rolling circle is r, and a point on the rolling circle generates the curve:<br />
 &nbsp;&nbsp;x=(R-r)cos.t+r.cos( (R-r/r)t)<br />
&nbsp;&nbsp;y=(R-r)sin.t-r.sin( (R-r/r)t)<br /><br />
<b>➽Advantages in Engineering Applications:</b><br />
<b>Compact Design:</b> Hypocycloids help in creating smaller, space-efficient mechanisms.<br />
<b>Smooth Motion:</b> The rolling motion provides continuous and precise paths.<br />
<b>Energy Efficiency:</b> Reduces wear and friction in mechanical systems.<br /><br />
        </div>

      )}
    </div>
  )
}
